### ISSUE TITLE
githubActionsを使用してCI/CDを作ろう

### ISSUE THREAD

**Issue by yoshiddddd** [backendTeamUnissi/DiscordBot_mokumoku#29]
# GitHub Actionsを使用したCI/CDパイプライン構築

## 目的
mainブランチへのpushが行われた際に、自動的にLambda関数へデプロイを行うCI/CDパイプラインを構築します。これにより開発効率の向上とデプロイミスの削減を図ります。

### 1. GitHub Actions用のワークフローファイル作成

`.github/workflows/deploy-lambda.yml` ファイルを作成し、以下の内容を実装します：

```yaml
name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Lambda
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run tests
        run: npm test
      
      - name: Create deployment package
        run: |
          npm prune --production
          zip -r function.zip . -x "*.git*" -x "*.github*" -x "tests/*" -x "*.zip"
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      
      - name: Deploy to Lambda
        run: |
          aws lambda update-function-code \
            --function-name discord-bot-mokumoku \
            --zip-file fileb://function.zip
      
      - name: Verify deployment
        run: |
          aws lambda get-function \
            --function-name discord-bot-mokumoku \
            --query 'Configuration.LastModified'
```

### 2. GitHub Secretsの設定

以下のシークレットをリポジトリに追加する必要があります：

1. `AWS_ACCESS_KEY_ID`: AWSのアクセスキーID
2. `AWS_SECRET_ACCESS_KEY`: AWSのシークレットアクセスキー

設定方法：
1. リポジトリの「Settings」タブをクリック
2. 左メニューから「Secrets and variables」→「Actions」を選択
3. 「New repository secret」ボタンをクリック
4. 名前と値を入力して保存

**注意**: デプロイ用のIAMユーザーには最小権限の原則に従って、必要最低限の権限だけを付与してください。具体的には以下の権限が必要です：
- `lambda:UpdateFunctionCode`
- `lambda:GetFunction`

### 3. Lambda関数の事前準備

CI/CDを構築する前に、以下の準備が必要です：

1. Lambda関数「discord-bot-mokumoku」が事前に作成されていること
2. 適切なIAMロールがLambda関数に割り当てられていること
3. Lambda関数の環境変数が適切に設定されていること

#### ステージング環境の設定
本番環境に影響を与えないようにするため、developブランチへのpushで別のLambda関数（ステージング環境）にデプロイするよう設定することも検討してください。

```yaml
on:
  push:
    branches:
      - main
      - develop
```

この場合、環境ごとにデプロイ先を分ける条件分岐も必要になります：

```yaml
- name: Deploy to Lambda
  run: |
    if [[ $GITHUB_REF == refs/heads/main ]]; then
      FUNCTION_NAME=discord-bot-mokumoku
    else
      FUNCTION_NAME=discord-bot-mokumoku-staging
    fi
    
    aws lambda update-function-code \
      --function-name $FUNCTION_NAME \
      --zip-file fileb://function.zip
```

#### 通知設定
デプロイ結果をDiscordやSlackに通知する機能も追加するとよいでしょう：

```yaml
- name: Notify deployment result
  if: always()
  uses: rtCamp/action-slack-notify@v2
  env:
    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    SLACK_TITLE: "Lambda Deployment"
    SLACK_MESSAGE: ${{ job.status == 'success' && 'デプロイが成功しました！' || 'デプロイが失敗しました。確認してください。' }}
    SLACK_COLOR: ${{ job.status == 'success' && 'good' || 'danger' }}
```

## タスク

- [ ] `.github/workflows/deploy-lambda.yml` ファイルの作成
- [ ] GitHubリポジトリにAWS認証情報のシークレットを設定
- [ ] テスト実行とビルドプロセスの確認
- [ ] 小規模な変更でワークフローのテスト
- [ ] (オプション) ステージング環境の設定
- [ ] (オプション) 通知設定の追加

## 参考資料
- [GitHub Actions公式ドキュメント](https://docs.github.com/ja/actions)
- [AWS Lambda公式ドキュメント](https://docs.aws.amazon.com/lambda/)
- [GitHub ActionsでのAWS認証](https://github.com/aws-actions/configure-aws-credentials)

実装に関する質問やフィードバックがあれば、このIssueでディスカッションしましょう。
